//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace CRYSTAL
{
	#region GAME OBJECT 
	
	public class CRYSTAL_Object : CRYSTAL_GUIElement {
		protected GameObject gameObject;
		public Vector3 position;
		
		public CRYSTAL_Object(GameObject _gameObject) : base() {
			gameObject = _gameObject;
		}
//		public CRYSTAL_Object (string _loadPath) : base() {
//			gameObject = LOADER.LoadGameObject(_loadPath);
//		}
		public GameObject Instantiate(Vector3 _position, GameObject _parent = null) {
			position = _position;
			
			CONSOLE.Log(CONSOLE_LOG_TYPE.CLONE, "CLONE (" + Tag, gameObject);
			GameObject newObject = (GameObject)Object.Instantiate(gameObject, _position, Quaternion.identity);
			
			if (_parent) {
				newObject.transform.parent = _parent.transform;
			}
			
			return newObject;
		}
	}
	
	#endregion
}

